### ISSUE TITLE
PicoFlasher "COM 10 Port Access Denied" when attempting to use in JRunner whilst NZXTCam is active

### ISSUE THREAD

**Issue by Speckie221** [X360Tools/PicoFlasher#3]
I dont know if this is an issue with the PicoFlasher or JRunner, but whenever NZXTCam Software is open (for use with NZXT coolers as I have a 280mm AIO) JRunner will report a "COM10 Port Access Denied" when trying to do anything that utilizes the PicoFlasher

**Comment by binquxxx** [comment]
Close nzxt cam?

**Comment by balika011** [comment]
Please file a bug report at NZXT. It's their issue.
