### ISSUE TITLE
Possibility to program glitch chips such as ACE v3 aswell?

### ISSUE THREAD

**Issue by The-Lord-of-Owls** [X360Tools/PicoFlasher#30]
Is pico flasher able to also program chips like the ACE v3 aswell? if not I'd like to know if this is something that could possibly be added as it would really be nice to eliminate the need entirely for programming equipment if we can also program those mod chips aswell as the xbox nand.

**Comment by nikdiklic** [comment]
I believe it is possible, but since the appearance of RGH3 not many people are willing to make such modification, because RGH3 makes glitch chips obsolete and unnecessary. I suggest you get more familiar with RGH3

**Comment by chackAJMCPE** [comment]
So how do we do it? (I accidentially broke cpu_pll_bypass pad.)
I would need to do an s-rgh

**Comment by The-Lord-of-Owls** [comment]
> I believe it is possible, but since the appearance of RGH3 not many people are willing to make such modification, because RGH3 makes glitch chips obsolete and unnecessary. I suggest you get more familiar with RGH3

RGH3 from what I've heard doesn't like to play well with dual nand on certain boards and with certain nand images. Thats kinda a deal breaker for me since I always dual nand

**Comment by chackAJMCPE** [comment]
I have finded a way. https://www.se7ensins.com/forums/threads/j-runner-with-extras-dirtypico360-program-timing-files-to-glitch-chips-using-a-pico.1844370/

**Comment by The-Lord-of-Owls** [comment]
Sorry for the really late reply but this helps quite a bit, thank you!
