### ISSUE TITLE
Any port for the RPi4

### ISSUE THREAD

**Issue by SamIsOnMC** [X360Tools/PicoFlasher#8]
Any port for the Raspberry Pi 4? I have one and i just want to save costs.

**Comment by SebastianBar** [comment]
They are different kinds of beasts... The Pi 4 does not have programmable I/O as the Pi Pico has, as far as I know.

**Comment by balika011** [comment]
Sorry, only the rp2040 has the needed hardware for this project. Therefore
it only works with the pico and other microcontrollers that use that chip.
