### ISSUE TITLE
Falcon xbox no consul found.

### ISSUE THREAD

**Issue by pacman362** [X360Tools/PicoFlasher#9]
I have a problem with a Falcon 360 running the latest dashboard but NOT being found by J-runner and Pico flasher ? I have just done another exact same Falcon and all is well ? but this one just shows up as CONSUL NOT FOUND x000000 (or something like this) in the output of J-runner????

Anyone had this issue before any words of advise.

PS: solder joints are fine I am skilled in p.c.b soldering.

**Comment by Shinjikuro95** [comment]
To be honest i had only work on trinity and corona, but there was one time when a corona made something similar and those are bad news cause it could mean that the nand its corrupted or damadge. On my case, the nand had been damadge with water by a previous owner so it was only matter of time. You should check the resistors around the nand.

Is not much but maybe it will lead you on the right path?

**Comment by Shinjikuro95** [comment]
The case i mentioned, the xbox boot up just fine also, but the nand couldn't be read of use so the internal storage was of no use in my case and i couldn't modify the nand

**Comment by pacman362** [comment]
Thanks again for the reply, I have just opened another Falcon and have the exact same issue so this rules our the caps or resistors, I have ordered another Pico for today so I will try with that tonight if this does not work I'm going to start a fresh with another laptop using a fresh operating system.

**Comment by Shinjikuro95** [comment]
Alright, i hope to find out if you figure this out cause it could help in the future. Good luck!

**Comment by pacman362** [comment]
I will update if I find a solution

**Comment by pacman362** [comment]
Ok quick update I ordered another Pico just in case and it turns out this has sorted the problems? So there must be some dodgy Picos on Amazon it did 1 Xbox and then I had this problem as above ! The new one has a darker coloured board as well which leads me to believe their may be fakes floating around ?

**Comment by pacman362** [comment]
Thanks for the reply I will test components later tonight, The Xbox boots
fine though?.
